
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-06
owner: ucsb-cs156-s25
repo_name: team02-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-helpreq-form","number":72,"title":"Riya helpreq form","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/72"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-tables","number":71,"title":"Timothy ucsb organizations tables","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/71"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-fixtures","number":70,"title":"yl - mir fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/70"}]
