
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-06
owner: ucsb-cs156-s25
repo_name: team02-s25-06
pull_requests: [{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-RecReq-IntegrationTests","number":129,"title":"Aryanchopra rec req integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/129"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-RecReq-EditPage","number":126,"title":"Aryanchopra rec req edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/126"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-RecReq-IndexPage","number":125,"title":"Aryanchopra rec req index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/125"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-create-RecReq-page","number":121,"title":"Aryanchopra create rec req page","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/121"}]
