
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-06
owner: ucsb-cs156-s25
repo_name: team02-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-py-backend-mir","number":67,"title":"copied files from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/67"},{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-helprequest-backend","number":66,"title":"riya - copy backend CRUD operations from team01 for the helprequests table","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/66"},{"author":{"id":"MDQ6VXNlcjM1MTE2OTc0","is_bot":false,"login":"sanjana-jilla-913","name":"Sanjana Jilla"},"headRefName":"sj-migrate-files","number":65,"title":"migrated files from team01 to team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/65"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-components","number":64,"title":"Timothy - add form for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/64"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-fixtures","number":63,"title":"Timothy - add javascript fixtures from ucsb organizations database table! ","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/63"}]
