
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-06
owner: ucsb-cs156-s25
repo_name: team02-s25-06
pull_requests: [{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-RecReq-form","number":109,"title":"Aryanchopra rec req form","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/109"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"aryanchopra-recreq-fixtures","number":108,"title":"Added fixtures in the Rec Rec table, will be used for storybook, tec.…","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/108"},{"author":{"id":"U_kgDOCMRpJg","is_bot":false,"login":"saeed-ar","name":""},"headRefName":"sa-FormatComponent_UCSBDiningCommonsMenuItem","number":107,"title":"Sa format component ucsb dining commons menu item","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/107"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-e2e","number":102,"title":"Yl mir e2e","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/102"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-integration-tests","number":101,"title":"Yl mir integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/101"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-edit","number":98,"title":"Yl mir edit","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/98"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-index","number":97,"title":"Yl mir index","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/97"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-create","number":96,"title":"Yl mir create","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/96"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-placeholder","number":92,"title":"Yl mir placeholder","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/92"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-table","number":91,"title":"Yl mir table","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/91"}]
