
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-06
owner: ucsb-cs156-s25
repo_name: team02-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-e2e","number":102,"title":"Yl mir e2e","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/102"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-integration-tests","number":101,"title":"Yl mir integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/101"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-edit","number":98,"title":"Yl mir edit","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/98"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-index","number":97,"title":"Yl mir index","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/97"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-create","number":96,"title":"Yl mir create","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/96"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-end2endtests","number":95,"title":"Timothy ucsb organizations end2endtests","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/95"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-placeholder","number":92,"title":"Yl mir placeholder","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/92"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-table","number":91,"title":"Yl mir table","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/91"},{"author":{"id":"U_kgDOCWXRgw","is_bot":false,"login":"timothy878","name":""},"headRefName":"Timothy-UCSBOrganizations-Integration-Tests","number":90,"title":"Timothy ucsb organizations integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/90"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mir-form","number":74,"title":"Yl mir form","url":"https://github.com/ucsb-cs156-s25/team02-s25-06/pull/74"}]
